#version: "3.7"

services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME=localstack
      - SERVICES=s3
      - AWS_DEFAULT_REGION=us-east-1
    ports:
      - "4566-4583:4566-4583"
    volumes:
      - ${TEMPDIR:-/var/lib/localstack}:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./script/localstack/s3/init-s3-bucket.sh:/docker-entrypoint-initaws.d/init-s3-bucket.sh


